### ISSUE TITLE
inspectTree with checksum is not working on large files

### ISSUE THREAD

**Issue by GuillaumeHemmen** [szwacz/fs-jetpack#101]
Hello,

I try to use the inspectTree function (`inspectTree(pathToFolder, { checksum: 'md5' })`) with the checksum set in the option. The folder I'm trying to inspect contains a few large files (up to ±4GB).

When doing so, I get the following error:

```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4008774437) is greater than 2 GB
    at tryCreateBuffer (fs.js:352:13)
    at Object.readFileSync (fs.js:388:14)
    at fileChecksum (<PATHTOPROJECT>/node_modules/fs-jetpack/lib/inspect.js:87:19)
```

I would expect the function to work without having this error.

**Comment by szwacz** [comment]
The problem here might be that synchronous operations need to load everything into memory, because need to do everything in one go. Does using `inspectTreeAsync` lead to the same error?

**Comment by GuillaumeHemmen** [comment]
Hello @szwacz,

Using inspectTreeAsync solved the issue.

Thanks a lot!

**Comment by szwacz** [comment]
Good... but bad at the same time :) I'll leave this issue open to investigate if this can be somehow fixed for sync operations.
